name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker image
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/comp7940_group_project_group13_container:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/comp7940_group_project_group13_container:latest

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name <app_name> \
          --resource-group <resource_group_name> \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/comp7940_group_project_group13_container:latest


